export const DASHBOARD_CONSTANT = {
    GET_PARTICIPANTS_FOR_STAFF: '/staff/dashboard/getParticipantsForDashBoardGrid',
    GET_CURRENT_STAFF_PROGRAMS: '/staff/program/getStaffPrograms',
    GET_ALL_STAFF_PROGRAMS: '/staff/program/getAllPrograms',
    GET_TASKS: '/staff/dashboard/getTasks',
    GET_ALERTS: '/staff/dashboard/getAlerts',
    GET_PARTICIPANTS_DATA: '/staff/dashboard/getAccountInfoAndParticipantRiskCount',
    GET_INTERVENTION_LIST: '/staff/task/intervention/initialize',
    SAVE_INTERVENTION_LOG_DETAILS: '/staff/task/intervention/saveLogDetails',
    GET_VITAL_TASKS: '/staff/dashboard/getVitalTask',
    GET_INTERVENTION_COMPLIANCE_LIST: '/staff/dashboard/getComplianceTask',
    UPDATE_READ_TASK_FLAG: '/staff/dashboard/updateReadFlag',
    POST_SET_INACTIVE_MEDICATION: '/staff/medication/setMedicationInActive/',
    ADD_LUNGS: '/staff/vitals/addVital',
    UPDATE_LUNGS: '/staff/vitals/updateLungVitalDetails',
    GET_LUNG_DATA_STATUS: '/staff/vitals/getValueStatusDetails/',
    ADD_DEVELOPMENT: '/staff/whbmi/addWhbmi',
    UPDATE_DEVELOPMENT: '/staff/whbmi/updateWhbmi',
    GET_ALL_SEARCHED_PARTICIPANT: '/staff/actionPlan/getActionPlanCareTeam/',
    REASSIGN_ACTION_PLAN_TASK: '/staff/actionPlan/reAssignActionPlanTask',
};

